java-sun modified jre man links and indentation

diff --git a/java-sun/PKGBUILD b/java-sun/PKGBUILD
--- a/java-sun/PKGBUILD
+++ b/java-sun/PKGBUILD
@@ -40,138 +40,133 @@ source=(http://download.java.net/dlj/binaries/jdk-${pkgver}-dlj-linux-${_arch}.b
 				'50b4f5ac4129097461d246645d73a622')
 
 build() {
-  cd ${srcdir}
-  mkdir unbundle-jdk
-  cd unbundle-jdk
-  sh ../jdk-${pkgver}-dlj-linux-$_arch.bin --accept-license
-  cd ..
-#  sh construct.sh unbundle-jdk linux-jdk linux-jre
+	cd ${srcdir}
+	mkdir unbundle-jdk
+	cd unbundle-jdk
+	sh ../jdk-${pkgver}-dlj-linux-$_arch.bin --accept-license
+	cd ..
 
-#  mkdir -p ${pkgdir}/opt/java
-#  cp -Ra ${srcdir}/unbundle-jdk/jdk1.6.0_21/* ${pkgdir}/opt/java
-  # Creating JRE directory...
-  # unpacking jars...
-  cd unbundle-jdk/jdk1.6.0_21
-  for i in $(find . -name '*.pack'); do
-	  jdir=$(dirname $i)
-	  jbase=$(basename $i .pack)
-	  if ! unpack200 $jdir/$jbase.pack $jdir/$jbase.jar; then
-		  echo "error unpacking $jdir/$jbase.jar"
-		  exit 1
-	  fi
-	  if [ ! -r $jdir/$jbase.jar ]; then
-	  	echo "missing $jdir/$jbase.jar"
-		exit 1
-	  else
-	  	#echo "  $jdir/$jbase.jar"
-		# remove pack file
-		rm $jdir/$jbase.pack
-	  fi
-  done
+	# Construct JDK/JRE
+	# https://jdk-distros.dev.java.net/source/browse/*checkout*/jdk-distros/trunk/utils/construct.sh
+	# unpacking jars...
+	cd unbundle-jdk/jdk1.6.0_21
+	for i in $(find . -name '*.pack'); do
+		jdir=$(dirname $i)
+		jbase=$(basename $i .pack)
+		if ! unpack200 $jdir/$jbase.pack $jdir/$jbase.jar; then
+			echo "error unpacking $jdir/$jbase.jar"
+			exit 1
+		fi
+		if [ ! -r $jdir/$jbase.jar ]; then
+			echo "missing $jdir/$jbase.jar"
+			exit 1
+		else
+			# remove pack file
+			rm $jdir/$jbase.pack
+		fi
+	done
 
+	# if this is a client installation...
+	compiler="$(bin/java -client -version 2>&1 | tail -n +3 | cut -d' ' -f1-4)"
+	if [ "X$compiler" = "XJava HotSpot(TM) Client VM" ]; then
+		# create the CDS archive
+		# creating the class data sharing archive...
+		if ! bin/java -client -Xshare:dump > /dev/null 2>&1; then
+			echo "returned error code $?"
+		fi
+	fi
 
-  # TODO See if not deprecated
-  # if this is a client installation...
-  compiler="`$jdkdir/bin/java -client -version 2>&1 | tail -n +3 | cut -d' ' -f1-4`"
-  if [ "X$compiler" = "XJava HotSpot(TM) Client VM" ]; then
-    # create the CDS archive
-    # creating the class data sharing archive...
-    if ! bin/java -client -Xshare:dump > /dev/null 2>&1; then
-      echo "returned error code $?"
-    fi
-  fi
+	# Setting up the JRE man pages...
+	mkdir -p jre/man/{,ja_JP.eucJP/}man1
+	# javaws.1 kinit.1 klist.1 ktab.1
+	for f in java.1 keytool.1 orbd.1 pack200.1 policytool.1 \
+		rmid.1 rmiregistry.1 servertool.1 tnameserv.1 unpack200.1; do
 
-  # setting up the JRE man pages...
-  mkdir -p jre/man/{,ja_JP.eucJP/}man1
-# javaws.1 kinit.1 klist.1 ktab.1
-  for f in java.1 keytool.1 orbd.1 pack200.1 policytool.1 rmid.1 rmiregistry.1 servertool.1 tnameserv.1 unpack200.1; do
+		mv man/man1/$f jre/man/man1/$f
+		ln -s jre/man/man1/$f man/man1/$f
 
-	mv man/man1/$f jre/man/man1/$f
-	ln -s jre/man/man1/$f man/man1/$f
+		mv man/ja_JP.eucJP/man1/$f jre/man/ja_JP.eucJP/man1/$f
+		ln -s jre/man/ja_JP.eucJP/man1/$f man/ja_JP.eucJP/man1/$f
+	  done
 
-	mv man/ja_JP.eucJP/man1/$f jre/man/ja_JP.eucJP/man1/$f
-	ln -s jre/man/ja_JP.eucJP/man1/$f man/ja_JP.eucJP/man1/$f
-  done
+	ln -s ja_JP.eucJP jre/man/ja
 
-  ln -s ja_JP.eucJP jre/man/ja
+	# Eliminating duplication between the JDK and JDK/jre...
+	# kinit klist ktab
+	for f in ControlPanel java javaws keytool orbd pack200 policytool \
+		rmid rmiregistry servertool tnameserv unpack200; do
 
-# eliminating duplication between the JDK and JDK/jre...
-# kinit klist ktab
-  for f in ControlPanel java javaws keytool orbd pack200 policytool rmid rmiregistry servertool tnameserv unpack200; do
-
-	rm bin/$f
-	ln -s jre/bin/$f bin/$f
-  done
+		rm bin/$f
+		ln -s ../jre/bin/$f bin/$f
+	done
 }
 
 package_jre() {
-  pkgdesc="Sun/Oracle's Java Runtime Environment"
-  depends=('glibc' 'libxtst')
-  provides=('j2re' 'java-runtime=6')
-  conflicts=('j2re' 'java-runtime')
-  replaces=('j2re')
-  install='jre.install'
+	pkgdesc="Sun/Oracle's Java Runtime Environment"
+	depends=('glibc' 'libxtst')
+	provides=('j2re' 'java-runtime=6')
+	conflicts=('j2re' 'java-runtime')
+	replaces=('j2re')
+	install='jre.install'
 
-  cd ${srcdir}/unbundle-jdk/jdk1.6.0_21
+	cd ${srcdir}/unbundle-jdk/jdk1.6.0_21
 
-  mkdir -p ${pkgdir}/opt/java
-  cp -R jre ${pkgdir}/opt/java
+	mkdir -p ${pkgdir}/opt/java
+	cp -R jre ${pkgdir}/opt/java
 
-  install -Dm755 ${srcdir}/jre.profile ${pkgdir}/etc/profile.d/jre.sh
+	install -Dm755 ${srcdir}/jre.profile ${pkgdir}/etc/profile.d/jre.sh
 
-  mkdir -p ${pkgdir}/usr/lib/mozilla/plugins
+	mkdir -p ${pkgdir}/usr/lib/mozilla/plugins
 
-  if [ "$CARCH" = "i686" ]; then
-    ln -s /opt/java/jre/lib/i386/libnpjp2.so ${pkgdir}/usr/lib/mozilla/plugins
-  else ln -s /opt/java/jre/lib/amd64/libnpjp2.so ${pkgdir}/usr/lib/mozilla/plugins
-  fi
+	if [ "$CARCH" = "i686" ]; then
+		ln -s /opt/java/jre/lib/i386/libnpjp2.so ${pkgdir}/usr/lib/mozilla/plugins
+	else	ln -s /opt/java/jre/lib/amd64/libnpjp2.so ${pkgdir}/usr/lib/mozilla/plugins
+	fi
 
-  mkdir -p ${pkgdir}/usr/share/licenses/jre
-  cp ${pkgdir}/opt/java/jre/COPYRIGHT ${pkgdir}/usr/share/licenses/jre
-  cp ${pkgdir}/opt/java/jre/LICENSE ${pkgdir}/usr/share/licenses/jre
-  cp ${pkgdir}/opt/java/jre/THIRDPARTYLICENSEREADME.txt ${pkgdir}/usr/share/licenses/jre
+	mkdir -p ${pkgdir}/usr/share/licenses/jre
+	cp ${pkgdir}/opt/java/jre/COPYRIGHT ${pkgdir}/usr/share/licenses/jre
+	cp ${pkgdir}/opt/java/jre/LICENSE ${pkgdir}/usr/share/licenses/jre
+	cp ${pkgdir}/opt/java/jre/THIRDPARTYLICENSEREADME.txt ${pkgdir}/usr/share/licenses/jre
 
-  # Fix system prefs folder (FS#18872)
-  install -dm755 ${pkgdir}/etc/.java/.systemPrefs
+	# Fix system prefs folder (FS#18872)
+	install -dm755 ${pkgdir}/etc/.java/.systemPrefs
 }
 
 package_jdk() {
-  pkgdesc="Sun/Oracle's Java Development Kit"
-  depends=('glibc' 'jre')
-  provides=('java-environment=6' 'j2sdk')
-  conflicts=('java-environment' 'j2sdk')
-  replaces=('j2sdk')
-  install='jdk.install'
+	pkgdesc="Sun/Oracle's Java Development Kit"
+	depends=('glibc' 'jre')
+	provides=('java-environment=6' 'j2sdk')
+	conflicts=('java-environment' 'j2sdk')
+	replaces=('j2sdk')
+	install='jdk.install'
 
+	cd ${srcdir}
 
-
-  cd ${srcdir}
-
-  #copy icon
-  install -Dm644 ${srcdir}/unbundle-jdk/jdk1.6.0_21/jre/lib/desktop/icons/hicolor/48x48/apps/sun-java.png \
+	#copy icon
+	install -Dm644 ${srcdir}/unbundle-jdk/jdk1.6.0_21/jre/lib/desktop/icons/hicolor/48x48/apps/sun-java.png \
 		 ${pkgdir}/usr/share/pixmaps/java.png
 
-  rm -rf unbundle-jdk/jdk1.6.0_21/jre
-  mkdir -p ${pkgdir}/opt
-  mv unbundle-jdk/jdk1.6.0_21 ${pkgdir}/opt/java
+	rm -rf unbundle-jdk/jdk1.6.0_21/jre
+	mkdir -p ${pkgdir}/opt
+	mv unbundle-jdk/jdk1.6.0_21 ${pkgdir}/opt/java
 
 
-  install -D -m755 ${srcdir}/jdk.profile ${pkgdir}/etc/profile.d/jdk.sh
+	install -D -m755 ${srcdir}/jdk.profile ${pkgdir}/etc/profile.d/jdk.sh
 
-  mkdir -p ${pkgdir}/usr/share/licenses/jdk
-  cp ${pkgdir}/opt/java/COPYRIGHT ${pkgdir}/usr/share/licenses/jdk
-  cp ${pkgdir}/opt/java/LICENSE ${pkgdir}/usr/share/licenses/jdk
-  cp ${pkgdir}/opt/java/THIRDPARTYLICENSEREADME.txt ${pkgdir}/usr/share/licenses/jdk
+	mkdir -p ${pkgdir}/usr/share/licenses/jdk
+	cp ${pkgdir}/opt/java/COPYRIGHT ${pkgdir}/usr/share/licenses/jdk
+	cp ${pkgdir}/opt/java/LICENSE ${pkgdir}/usr/share/licenses/jdk
+	cp ${pkgdir}/opt/java/THIRDPARTYLICENSEREADME.txt ${pkgdir}/usr/share/licenses/jdk
 
-  #desktop entries
-  install -Dm644 ${srcdir}/java-control-panel.desktop \
+	#desktop entries
+	install -Dm644 ${srcdir}/java-control-panel.desktop \
   		 ${pkgdir}/usr/share/applications/java-control-panel.desktop
-  install -Dm644 ${srcdir}/java-monitoring-and-management-console.desktop \
+	install -Dm644 ${srcdir}/java-monitoring-and-management-console.desktop \
   		 ${pkgdir}/usr/share/applications/java-monitoring-and-management-console.desktop
-  install -Dm644 ${srcdir}/java-policy-settings.desktop \
+	install -Dm644 ${srcdir}/java-policy-settings.desktop \
   		 ${pkgdir}/usr/share/applications/java-policy-settings.desktop
-  install -Dm644 ${srcdir}/java-visualvm.desktop \
+	install -Dm644 ${srcdir}/java-visualvm.desktop \
   		 ${pkgdir}/usr/share/applications/java-visualvm.desktop
-  install -Dm644 ${srcdir}/java-web-start.desktop \
+	install -Dm644 ${srcdir}/java-web-start.desktop \
   		 ${pkgdir}/usr/share/applications/java-web-start.desktop
 }
